package com.panmin.model;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.NotNull;
import org.greenrobot.greendao.annotation.Property;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "TASK_CALL".
 */
@Entity
public class TaskCall {

    @Id(autoincrement = true)
    private Long _id;

    @Property(nameInDb = "id")
    private String id;

    @Property(nameInDb = "userId")
    @NotNull
    private String userId;

    @Property(nameInDb = "title")
    private String title;

    @Property(nameInDb = "remarks")
    private String remarks;

    @Property(nameInDb = "remindTime")
    private long remindTime;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public TaskCall() {
    }

    public TaskCall(Long _id) {
        this._id = _id;
    }

    @Generated
    public TaskCall(Long _id, String id, String userId, String title, String remarks, long remindTime) {
        this._id = _id;
        this.id = id;
        this.userId = userId;
        this.title = title;
        this.remarks = remarks;
        this.remindTime = remindTime;
    }

    public Long get_id() {
        return _id;
    }

    public void set_id(Long _id) {
        this._id = _id;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @NotNull
    public String getUserId() {
        return userId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUserId(@NotNull String userId) {
        this.userId = userId;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getRemarks() {
        return remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    public long getRemindTime() {
        return remindTime;
    }

    public void setRemindTime(long remindTime) {
        this.remindTime = remindTime;
    }

    // KEEP METHODS - put your custom methods here
    private long createTime;

    public long getCreateTime() {
        return createTime;
    }

    public void setCreateTime(long createTime) {
        this.createTime = createTime;
    }
    // KEEP METHODS END

}
